steps:
  - label: "Validation check"
    command: ./scripts/validation_tests.sh
    key: "validation-check"
    soft_fail:
      - exit_status: 1
    command: |
      if [ $$(buildkite-agent step get "outcome" --step "validation-check") == "passed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload
         steps:
           - block: ":rocket: this failed?"

      YAML
      fi
