steps:
  - label: "Validation check"
    command: ./scripts/validation_tests.sh
    tt:
    key: "validation-check"
  - label: "Run regression only if validation check is passed"
    depends_on: "validation-check"
    command: |
      if [ $$(buildkite-agent step get "outcome" --step "validation-check") != "passed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload
         steps:
           - label: "Run Regression"
           - block: ":rocket: failed?"

      YAML
      fi
