steps:
  - label: "Validation check"
    command: ./scripts/validation_tests.sh
    key: "validation-check"
  - label: "Run regression only if validation check is passeds"
    depends_on: "validation-check"
    command: |
      if [ $$(buildkite-agent step get "outcome" --step "validation-check") == "" ]; then
         cat <<- YAML | buildkite-agent pipeline upload
         steps:
           - block: ":rocket: Are we ready?"

      YAML
      fi
